### ISSUE TITLE
A lot of enums variants aren't accessible?

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/sys#24]
I tried to use [StateFlags](http://gtk-rs.org/docs/gtk/struct.StateFlags.html) variants but had to use from_bits method to make it work. This is absolutely terrible and should be changed.

cc @gkoz

**Comment by gkoz** [comment]
Yeah https://github.com/gtk-rs/gir/pull/229 is supposed to solve this once it's complete.

**Comment by gkoz** [comment]
To elaborate, this isn't a sys crate issue actually. The sys crates do export the consts (e.g. `GTK_STATE_FLAG_ACTIVE`) of course because that's what the `bitflags!` macro does. The problems are:

* Rust still lacks good associated items support so you can't have associated constants like `StateFlags::ACTIVE` etc.
* We don't make these consts available in the high-level crates and that's what https://github.com/gtk-rs/gir/pull/229 is about.
* The `StateFlags` documentation should link to those consts: https://github.com/gtk-rs/gir/issues/230
